# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
      
      - image: circleci/mysql:5.6.0
        
        environment:
          MYSQL_DATABASE: movie
          MYSQL_USER: root
          MYSQL_PASSWORD: root
      
    steps:
      - checkout
    
      - run:
          name: Install Dependencies
          command: go mod download
          working_directory: ~/repo/front
    
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            mv config.demo.ini config.ini
            go test -v
          working_directory: ~/repo/front
      - store_test_results:
          path: /tmp/test-reports
