# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
      - image: circleci/mysql:5.6.50
        environment:
          MYSQL_DATABASE: movie
          MYSQL_USER: golang
          MYSQL_PASSWORD: root
   
    steps:
      - checkout
    
      - run:
          name: Install Dependencies
          command: go mod download
          working_directory: ~/repo/front
          
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m    
    
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            go test --json >> /tmp/test-reports/unit-tests.json
          working_directory: ~/repo/front
      - store_test_results:
          path: /tmp/test-reports
